/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: CCU8 Timer Example
*              for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2021, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/

#include "cybsp.h"
#include "cy_utils.h"
#include "xmc_ccu8.h"

/*******************************************************************************
* Macros
*******************************************************************************/
/*Define macros for XMC14x Boot kit*/
#ifdef TARGET_KIT_XMC14_BOOT_001
#define TIMER_0_PERIOD_MATCH_EVENT_PRIORITY   3
#define TIMER_0_PERIOD_MATCH_EVENT_HANDLER    IRQ_Hdlr_1
#define PERIOD_MATCH_COUNT                    (46874U)
#define PRESCALER_INITVAL                     (11U)
#define XMC_CCU8_SERVICE_REQUEST_ID           XMC_CCU8_SLICE_SR_ID_0
#define TIMER_0_PERIOD_MATCH_EVENT_IRQN       IRQ1_IRQn
#endif

/*Define macros for XMC47x Relax kit*/
#ifdef TARGET_KIT_XMC47_RELAX_V1
#define TIMER_0_PERIOD_MATCH_EVENT_PRIORITY   61
#define TIMER_0_PERIOD_MATCH_EVENT_HANDLER    IRQ_Hdlr_61
#define PERIOD_MATCH_COUNT                    (35155U)
#define PRESCALER_INITVAL                     (12U)
#define XMC_CCU8_SERVICE_REQUEST_ID           XMC_CCU8_SLICE_SR_ID_1
#define TIMER_0_PERIOD_MATCH_EVENT_IRQN       CCU80_1_IRQn
#endif

#define SLICE_PTR         CCU80_CC81
#define MODULE_PTR        CCU80
#define MODULE_NUMBER     (0U)
#define SLICE_NUMBER      (1U)


/*******************************************************************************
* Global Variables
*******************************************************************************/
static volatile bool timer_interrupt_flag = false;

/*******************************************************************************
* Data Structure
*******************************************************************************/
/*Initialization data of a CCU8 Slice*/
XMC_CCU8_SLICE_COMPARE_CONFIG_t g_timer_object =
{
    .timer_mode          = XMC_CCU8_SLICE_TIMER_COUNT_MODE_EA,       /*Select Edge aligned or Centre Aligned*/
    .monoshot            = false,                                    /*Repetitive mode: continuous mode of operation*/
    .shadow_xfer_clear   = false,                                    /*Select PR and CR shadow xfer happen when timer is cleared*/
    .dither_timer_period = false,                                    /*Select for the period of the timer dither*/ 
    .dither_duty_cycle   = false,                                    /*Select for the compare match of the timer dither*/
    .prescaler_mode      = XMC_CCU8_SLICE_PRESCALER_MODE_NORMAL,     /*Normal or floating prescaler mode selection*/
    .mcm_ch1_enable      = false,                                    /*Select Multi-Channel mode for compare channel 1 enable*/
    .mcm_ch2_enable      = false,                                    /*Select Multi-Channel mode for compare channel 2 enable*/
    .slice_status        = XMC_CCU8_SLICE_STATUS_CHANNEL_1,          /*Selection for which of the two channels drives the slice status output*/
    .asymmetric_pwm      = false,                                    /*Select if the PWM be a function of the 2 compare channels rather than period value*/
    .prescaler_initval   = PRESCALER_INITVAL,                        /*Prescaler divider value*/
    .float_limit         = 0U,                                       /*The max value which the prescaler divider can increment to*/
    .dither_limit        = 0U,                                       /*The value that determines the spreading of dithering*/
    .timer_concatenation = false                                     /*Enables the concatenation of the timer*/
};

/*******************************************************************************
* Function Name: TIMER_0_PERIOD_MATCH_EVENT_HANDLER
********************************************************************************
* Summary:
* This is the interrupt handler function for the CCU8 timer period match interrupt.
*
* Parameters:
*  none
*
* Return:
*  void
*
*******************************************************************************/
void TIMER_0_PERIOD_MATCH_EVENT_HANDLER(void)
{
    timer_interrupt_flag = true;
}

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function.It sets up a CCU8 timer to period match interrupt.
* The main while loop checks for the elapsed time due to CCU8 timer period match
* event and toggles an LED at approximately 1Hz.
*
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    /*Initialize the device and board peripherals*/
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    /*Set CCU8 Module clock*/
    XMC_CCU8_SetModuleClock(MODULE_PTR, XMC_CCU8_CLOCK_SCU);

    /*Set CCU8 Module Init*/
    XMC_CCU8_Init(MODULE_PTR, XMC_CCU8_SLICE_MCMS_ACTION_TRANSFER_PR_CR);

    /*Enable the CCU8 Slice Clock*/
    XMC_CCU8_EnableClock(MODULE_PTR, SLICE_NUMBER);

    /*Start the prescaler and restore clocks to slices*/
    XMC_CCU8_StartPrescaler(MODULE_PTR);

    /*Initialize the CCU8 Slice*/
    XMC_CCU8_SLICE_CompareInit(SLICE_PTR, &g_timer_object);

    /*Program a value into Period Match register*/
    XMC_CCU8_SLICE_SetTimerPeriodMatch(SLICE_PTR, PERIOD_MATCH_COUNT);

    /*Enable shadow transfer*/
    XMC_CCU8_EnableShadowTransfer(MODULE_PTR, XMC_CCU8_SHADOW_TRANSFER_SLICE_1);

    /*Enable Period Match event*/
    XMC_CCU8_SLICE_EnableEvent(SLICE_PTR, XMC_CCU8_SLICE_IRQ_ID_PERIOD_MATCH);

    /*Connect Period Match event to Service Request lines -SRx*/
    XMC_CCU8_SLICE_SetInterruptNode(SLICE_PTR, XMC_CCU8_SLICE_IRQ_ID_PERIOD_MATCH, XMC_CCU8_SERVICE_REQUEST_ID);

    /*Clears IDLE mode for the slice*/
    XMC_CCU8_EnableClock(MODULE_PTR, SLICE_NUMBER);

    /*Start CCU8 Timer*/ 
    XMC_CCU8_SLICE_StartTimer(SLICE_PTR);

    #ifdef TARGET_KIT_XMC14_BOOT_001
    /*Interrupt Multiplexer configuration*/
    XMC_SCU_SetInterruptControl(TIMER_0_PERIOD_MATCH_EVENT_IRQN, XMC_SCU_IRQCTRL_CCU80_SR0_IRQ1);
    /*Set priority*/
    NVIC_SetPriority(TIMER_0_PERIOD_MATCH_EVENT_IRQN, TIMER_0_PERIOD_MATCH_EVENT_PRIORITY);
    #endif

    #ifdef TARGET_KIT_XMC47_RELAX_V1
    /*Set Interrupt priority*/
    NVIC_SetPriority(TIMER_0_PERIOD_MATCH_EVENT_IRQN, NVIC_EncodePriority(NVIC_GetPriorityGrouping(), TIMER_0_PERIOD_MATCH_EVENT_PRIORITY, 0));
    #endif

    /*Enable IRQ*/
    NVIC_EnableIRQ(TIMER_0_PERIOD_MATCH_EVENT_IRQN);

    /*Infinite loop*/
    while (1)
    {
        /*Check if timer elapsed (interrupt fired) and toggle the LED*/
        if (timer_interrupt_flag)
        {
            /*Clear the flag */
            timer_interrupt_flag = false;
            /* Toggle the USER LED state */
            XMC_GPIO_ToggleOutput(CYBSP_USER_LED_PORT, CYBSP_USER_LED_PIN);
        }

    }
}

/* [] END OF FILE */
